version: '3.0'
services:
  postgres:
    restart: unless-stopped
    image: postgres:10
    container_name: enhanced_city_db
    environment:
      - POSTGRES_USER=${SPATIAL_MULTIMEDIA_DB_USER}
      - POSTGRES_PASSWORD=${SPATIAL_MULTIMEDIA_DB_PASSWORD}
      - POSTGRES_DB=${SPATIAL_MULTIMEDIA_DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - ${SPATIAL_MULTIMEDIA_DB_PORT}:5432
  app:
    container_name: enhanced_city_api
    build: .
    ports:
      - 1525:5000
    volumes:
      - .:/api
    depends_on:
      - postgres
